@baseUrl = http://localhost:8080
@auth_token = add_token

### Get User by ID
GET {{baseUrl}}/api/users/{Id}
Authorization: Bearer {{auth_token}}

### Get all
GET {{baseUrl}}/api/users
Authorization: Bearer {{auth_token}}